### GET request to example server
POST http://localhost:3000/api/admin/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin"
}

### POST create event
POST http://localhost:3000/api/event
Content-Type: application/json
X-API-Key: 7901945a-de16-11ef-bb57-4c24ce35582e

{
  "name": "Event kecoak sigma",
  "description": "Hunting Kecoak",
  "start_time": "2025-01-01",
  "end_time": "2025-01-02"
}


### GET find by all
GET http://localhost:3000/api/event
ACCEPT: application/json
X-API-Key: 14dd7c0a-8656-4046-81df-58eb0b0cdc5e

### GET find by id
GET http://localhost:3000/api/event/7
ACCEPT: application/json
X-API-Key: 14dd7c0a-8656-4046-81df-58eb0b0cdc5e

### PUT update certain row
PUT http://localhost:3000/api/event/7
Content-Type: application/json
X-API-Key: 8c7da5a3-9e20-441d-912f-6b251478c43f

{
  "name": "Kecoak Hunting",
  "description": "Kecoak yang menjijikkan",
  "start_time": "2025-01-01",
  "end_time": "2025-01-02"
}

### DELETE by id
DELETE http://localhost:3000/api/event/7
Accept: application/json
X-API-Key: 14dd7c0a-8656-4046-81df-58eb0b0cdc5e

### POST create attendee
POST http://localhost:3000/api/attendee
Content-Type: application/json
X-API-Key: 7901945a-de16-11ef-bb57-4c24ce35582e

{
  "name": "AliKoplak",
  "email": "ali@alisigma.com"
}

### GET find by all
GET http://localhost:3000/api/attendee
ACCEPT: application/json
X-API-Key: 8c7da5a3-9e20-441d-912f-6b251478c43f

### GET find by Id
GET http://localhost:3000/api/attendee/2
ACCEPT: application/json
X-API-Key: 8c7da5a3-9e20-441d-912f-6b251478c43f

### PUT update certain row
PUT http://localhost:3000/api/attendee/1
Content-Type: application/json
X-API-Key: 8c7da5a3-9e20-441d-912f-6b251478c43f

{
  "name": "terbaruk",
  "email": "newest@gmail.com"
}

### DELETE by id
DELETE http://localhost:3000/api/attendee/1
Accept: application/json
X-API-Key: 8c7da5a3-9e20-441d-912f-6b251478c43f

### POST create New Ticket
POST http://localhost:3000/api/ticket
Content-Type: application/json
X-API-Key: 7901945a-de16-11ef-bb57-4c24ce35582e

{
  "event_id": "1",
  "attendee_id": "1"
}

### GET find by Id
GET http://localhost:3000/api/ticket/4
ACCEPT: application/json
X-API-Key: 7901945a-de16-11ef-bb57-4c24ce35582e

### GET ALL
GET http://localhost:3000/api/ticket
ACCEPT: application/json
X-API-Key: 7901945a-de16-11ef-bb57-4c24ce35582e

### Cancel A Certain Ticket
PUT http://localhost:3000/api/ticket/4
ACCEPT: application/json
X-API-Key: 7901945a-de16-11ef-bb57-4c24ce35582e