### GET request to example server
POST http://localhost:3000/api/admin/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin"
}

### POST create event
POST http://localhost:3000/api/event
Content-Type: application/json
X-API-Key: 8c7da5a3-9e20-441d-912f-6b251478c43f

{
  "name": "dddddd",
  "description": "Ya sdd",
  "start_time": "2025-01-01",
  "end_time": "2025-01-02"
}


### GET find by all
GET http://localhost:3000/api/event
ACCEPT: application/json
X-API-Key: 14dd7c0a-8656-4046-81df-58eb0b0cdc5e

### GET find by id
GET http://localhost:3000/api/event/7
ACCEPT: application/json
X-API-Key: 14dd7c0a-8656-4046-81df-58eb0b0cdc5e

### PUT update certain row
PUT http://localhost:3000/api/event/7
Content-Type: application/json
X-API-Key: 14dd7c0a-8656-4046-81df-58eb0b0cdc5e

{
  "name": "terbaruk",
  "description": "kcoak",
  "start_time": "2025-01-01",
  "end_time": "2025-01-02"
}

### DELETE by id
DELETE http://localhost:3000/api/event/7
Accept: application/json
X-API-Key: 14dd7c0a-8656-4046-81df-58eb0b0cdc5e