// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"jirbthagoras/event-management/app"
	"jirbthagoras/event-management/controller"
	"jirbthagoras/event-management/repository"
	"jirbthagoras/event-management/service"
	"net/http"
)

// Injectors from injector.go:

func InitializedServer() *http.Server {
	adminRepositoryImpl := repository.NewAdminRepositoryImpl()
	db := app.NewDB()
	validate := app.NewValidator()
	adminServiceImpl := service.NewAdminServiceImpl(adminRepositoryImpl, db, validate)
	adminControllerImpl := controller.NewAdminControllerImpl(adminServiceImpl)
	controllers := app.NewControllers(adminControllerImpl)
	router := app.NewRouter(controllers)
	server := app.NewServer(router)
	return server
}

// injector.go:

var adminControllerSet = wire.NewSet(repository.NewAdminRepositoryImpl, wire.Bind(new(repository.AdminRepository), new(*repository.AdminRepositoryImpl)), service.NewAdminServiceImpl, wire.Bind(new(service.AdminService), new(*service.AdminServiceImpl)), controller.NewAdminControllerImpl, wire.Bind(new(controller.AdminController), new(*controller.AdminControllerImpl)))
